# Generated by Django 3.2.16 on 2022-10-30 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranges', models.CharField(max_length=50)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CUTS.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Cut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=50)),
                ('roll_width', models.IntegerField()),
                ('roll_no', models.IntegerField()),
                ('roll_size', models.IntegerField()),
                ('location', models.CharField(max_length=3)),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='range', to='CUTS.range')),
            ],
        ),
    ]
