# Generated by Django 3.2.16 on 2022-11-01 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CUTS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='range',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Supplier', to='CUTS.supplier'),
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolls', models.CharField(max_length=50)),
                ('ranges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Range', to='CUTS.range')),
            ],
        ),
        migrations.AlterField(
            model_name='cut',
            name='roll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Roll', to='CUTS.roll'),
        ),
    ]
