# Generated by Django 3.2.16 on 2022-11-01 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CUTS', '0002_auto_20221101_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cut',
            old_name='roll',
            new_name='rolls',
        ),
        migrations.RemoveField(
            model_name='cut',
            name='roll_size',
        ),
        migrations.AddField(
            model_name='cut',
            name='rollsizes',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, related_name='Rollsize', to='CUTS.roll'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roll',
            name='rollsizes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
            preserve_default=False,
        ),
    ]
