# Generated by Django 3.2.16 on 2022-11-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUTS', '0003_auto_20221101_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cut',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='cut',
            name='location',
        ),
        migrations.RemoveField(
            model_name='cut',
            name='roll_width',
        ),
        migrations.AddField(
            model_name='roll',
            name='colour',
            field=models.CharField(default='Colour', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roll',
            name='location',
            field=models.CharField(default='COLOUR', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roll',
            name='roll_width',
            field=models.IntegerField(default='Colour'),
            preserve_default=False,
        ),
    ]
