# Generated by Django 3.2.16 on 2022-11-01 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CUTS', '0004_auto_20221101_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cut',
            name='rolls',
        ),
        migrations.RemoveField(
            model_name='roll',
            name='rolls',
        ),
    ]
